### ISSUE TITLE
Unresponsive application 

### ISSUE THREAD

**Issue by wichtounet** [schulmar/Templar#6]
Hi, 

I'm trying to use this application to visualize the results from templight, but without success so far. 

I have used templight and generated a whole bunch of pbf files. I converted one of them into an xml with the templight-tools and then loaded it in Templar. The loading seemed to work but as soon as I try one of the buttons, the application hangs at 100% CPU and it has been hanging for several minutes. Am I doing something ? 

Are my files simply too big ?

Is there another way to visualize the templight results ? I cannot install KCacheGrind and I haven't seen anything of direct value in the text output. 

Thanks

**Comment by schulmar** [comment]
> Are my files simply too big ?
Well, how big are they?

I am sorry about the confusion but basically the only *really* working state is the initial port to Qt5.
All other states are work in progress and are not guaranteed to function.
Obviously, this is bad as the newer templight outputs do not work directly with the old code.
Which version (branch/commit) did you try?

I meant to address these issues for a while but I am swamped with other tasks.

Anyways, moving forward with this issue would require the ability to reproduce it.
Could you give an example C++ file whose templight output results in problems?

**Comment by wichtounet** [comment]
> Well, how big are they?

The PBF file was 3.1MB and the resulting XML file was 24M. 

> I am sorry about the confusion but basically the only really working state is the initial port to Qt5.
All other states are work in progress and are not guaranteed to function.

Oh, I didn't know it was in this state. 

> Which version (branch/commit) did you try?

I tried the last master version of templight/templight-tools/templar/

> I meant to address these issues for a while but I am swamped with other tasks.

No worry

> Could you give an example C++ file whose templight output results in problems?

Unfortunately, this is a large project (https://github.com/wichtounet/etl). I'm trying to find the culprit in compilation time. I simply compiled the complete test suite with templight and took one of the resulting PBF file.

**Comment by schulmar** [comment]
> The PBF file was 3.1MB and the resulting XML file was 24M. 

Okay, that should definitely be manageable, I thought the files would be in the order of 1GB upwards.

> I tried the last master version of templight/templight-tools/templar/

I am mainly interested in the branch of templar that you used: master or feature/templight2?

> Unfortunately, this is a large project (https://github.com/wichtounet/etl).
Well, it is open source so I might take a look at it when I find the time.
Is there anything I should know about how to set up this project?

>  I'm trying to find the culprit in compilation time. I simply compiled the complete test suite with templight and took one of the resulting PBF file. 

I am afraid that the Templar tool is not yet in the shape to offer you that kind of information. KCacheGrind would probably be your best bet, short of writing your own tool to give you a summary report. Templar so far only visualizes the instantiation graph and allows you to step through it.

**Comment by wichtounet** [comment]
> Okay, that should definitely be manageable, I thought the files would be in the order of 1GB upwards.

No, it's not that bad :P

> I am mainly interested in the branch of templar that you used: master or feature/templight2?

master

> Well, it is open source so I might take a look at it when I find the time.
> Is there anything I should know about how to set up this project?

You just need to clone it recusively for the submodules, and normally there should not be any issue with recent clang (guaranteed by templight). You can set CXX and LD to templight++ and add the templight flags to EXTRA_CXX_FLAGS and they will be picked by the makefile. 

> I am afraid that the Templar tool is not yet in the shape to offer you that kind of information. KCacheGrind would probably be your best bet, short of writing your own tool to give you a summary report. Templar so far only visualizes the instantiation graph and allows you to step through it.

This would already be a good information for me :) 

I'll give a try to KCacheGrind once I get the time to install a new virtual machine.

**Comment by schulmar** [comment]
Okay, I took the trace of the file `trigo.cpp` (which matched your description) and could reproduce  the problem.

The master version of Templar reads the old templight traces, which are written at `sourcefilepath.trace.xml`. The output from templight2.0 is named (e.g.) `trigo.cpp.o.memory.trace.xml`. The rather dumb code in Templar then tries to find `trigo.cpp.o.memory` which doesn't exist and hangs.

Working around that by moving and renaming the trace file I just ran into graphviz complaining about improperly UTF-8 encoded values. 

I'll have a look at the newer version of Templar which might work better.

**Comment by schulmar** [comment]
After fixing the UTF-8 issue the program now hangs in graphviz trying to layout the instantiation graph. I think the program has not been tested with "real world data" so far ;)

**Comment by wichtounet** [comment]
Glad to be of "real-world" service ;)

I can do more testing in the future if you want.

**Comment by schulmar** [comment]
I have pushed some changes to the branch feature/templight2

In this version you can open the .pbf directly from Templar so you don't need to convert.

I reduced the depth of the tree that is displayed to 3 elements (2 for the first level) because of the large fanout factors involved (the root had >5k entries, later entries ~80).

Graphviz may still take a while but on my machine it is below 10s.
For your use case you should probably make use of the list on the lower right and sort it by time consumption.

**Comment by wichtounet** [comment]
I tried the branch feature/templight2 but I haven't been able to compile it. 

There is an error in traceentry.h:112 which causes:

```
/usr/include/boost/type_traits/is_pod.hpp:44:13: error: incomplete type 'const Templar::TraceEntry' used in type trait expression
            BOOST_INTERNAL_IS_POD(T)

/home/wichtounet/build/Templar/traceentry.h:33:8: note: definition of 'Templar::TraceEntry' is not complete until the closing '}'
struct TraceEntry {
```

It comes from the fact that boost iterator is using the is_pod traits on the template parameter and therefore you cannot use it before the class is complete. 

Which version of Boost did you use ? I have the 1.56.

**Comment by schulmar** [comment]
I am running on 1.60 but this code has been around for a while (I believe it has seen boost 1.56 as well ;)
I assume the compiler is what makes the difference here.

Anyways, the iterator should use a reference as the value type. I pushed a change that should avoid this problem.

**Comment by wichtounet** [comment]
The error is gone with your changes. 

I tried again and now I have other errors: 

with clang 3.5 and clang 3.7: 

```
/home/wichtounet/build/Templar/tracereaders/tracereader.cpp:62:25: error: no matching function for call to 'removeExtension'
        removeExtension(removeExtension(traceFileName, {"xml", "yaml", "pbf"}),
                        ^~~~~~~~~~~~~~~
/home/wichtounet/build/Templar/tracereaders/tracereader.cpp:48:9: note: candidate function not viable: cannot convert initializer list argument to 'QStringList'
QString removeExtension(QString path, QStringList extensionsToRemove) {
```

That is probably because I have Qt4 which is not C++11 ready ?

g++5.3 and g++4.9.3 actually compiles the code, but then it fails with undefined references to protobuf, it may be due to abi differences. I'll have to check again.

**Comment by schulmar** [comment]
I cannot reproduce the error on my end, even when using clang instead of gcc. Which version of Qt4 are you using?

**Comment by wichtounet** [comment]
I got 4.8.6, but this may not be the issue. I'll try to investigate more the protobuf undefined references next week.

**Comment by wichtounet** [comment]
I fixed the undefined references, I'm now able to run Templar :)

It worked with the previous XML file I got. I can already see that I'm instantiating way too much templates :P Thanks ;)

I still have to figure out how to use it in my case and I've got some questions and problems though. I hope I don't waste too much of your time. 

Is there a way to see the number of instantiations of a template ? 
Is there a way to see some global statistics for easy comparison ? For instance total number of instantiations, total duration or something of that kind ? 
In the table, why are some template without any types (I have some X<Z> and some Y (no template arguments)) ? I have the same in the graph, for instance std::forward<X> and some std::forward with no arguments. 
In the table, the duration is summed over all the children ?

I have two Qt errors when I start the program: 

> Object::connect: No such slot QTableView::sortByColumn(int,)
> Object::connect: No such slot QGraph::follow()

When I launch Templar for another directory and I try to open directly a trace file, I get a segmentation fault: 

> TraceReader::build( "/home/wichtounet/dev/etl/debug/test/src/fast_matrix.cpp.o.memory.trace.pbf" ) 
> [1]    19203 segmentation fault  ./Templar

(in debug mode this opens a window with a path issue on a header file). So I guess it is mandatory to run it from the directory where the build took place. When I run from the good directory, I can load trace files directly (no more needs for templar-tools :) ).

**Comment by wichtounet** [comment]
I also get some empty nodes (no text in them) in the tree, is that normal ? They are clickable and have childrens.

**Comment by schulmar** [comment]
> Is there a way to see the number of instantiations of a template ?
> Is there a way to see some global statistics for easy comparison ? For instance total number of instantiations, total duration or something of that kind ? 

I presume you mean the number of instantiations from all different sources?
There are no summary reports so far. I believe that KCacheGrind could offer something along that line although I have not tested that.

I would be willing to consider adding these statistics but that would require more information on what you are interested in. E.g.:

total number of instantiations: Do you mean per template class or in the whole compilation process? What about system library instantiations and other "uninteresting" instantiations?
total duration: again per template or just how long the overall compilation took?
If we are going forward with this I would like to have an extra issue open for that to better keep track of the progress.

> In the table, why are some template without any types (I have some X and some Y (no template arguments)) ? I have the same in the graph, for instance std::forward and some std::forward with no arguments. 

Does this happen when loading the .pbf file as well? While looking through the .xml I saw many such instances which means that these errors seem to come from the trace. I also noticed that the converted xml file does not always contain the same contents as the .pbf. When there is really a difference this would likely be a bug in templight's convert tool. However, let me stress that the xml format is only supported for legacy support. Moving forward the .pbf files are intended to be the core format.

> In the table, the duration is summed over all the children ?

The duration is calculated from two timestamps that are taken just before and just after the template instantiation within templight began/finished. Therefore, I assume that it contains the children's instantiation times as well.

> I have two Qt errors when I start the program:
> 
> >    Object::connect: No such slot QTableView::sortByColumn(int,)
> >    Object::connect: No such slot QGraph::follow()

That is most likely an artifact of merging uncompleted work from a fork. As far as I know this is more of a cosmetic problem so not very high on the priority list. You could open an extra issue if it bothers you that much.

> When I launch Templar for another directory and I try to open directly a trace file, I get a segmentation fault:
> 
> >    TraceReader::build( "/home/wichtounet/dev/etl/debug/test/src/fast_matrix.cpp.o.memory.trace.pbf" )
> >    [1] 19203 segmentation fault ./Templar

That should not happen. By `for another directory` you mean you are in another directory than the build directory and launch Templar? I cannot reproduce the problem.

To explain what is happening here: Templar automatically tries to open the last trace that was loaded. It seems the segfault is occuring during loading this file. Does it still exist?

Additionally, the traces contain relative paths to the files containing the respective template definitions. In the last commits I added the dialog to allow the user to point Templar to where the build was taking place. This was added because previously the trace files were assumed to lie in the same folder as the source files, which prevents using Templar on out-of-source build traces. (The program can still run with wrong paths but it won't display/highlight the source in the respective view.)
Could you please write up a more detailed description of how to reproduce this in an extra ticket?

**Comment by schulmar** [comment]
> I also get some empty nodes (no text in them) in the tree, is that normal ? They are clickable and have childrens. 

I have seen some empty nodes in the .xml file so it might be that this is another artifact that is already in the trace files.

**Comment by wichtounet** [comment]
Thanks for your answers :) 

I will open other issues for forward discussions on the open points.
